# Generated by Django 3.1.2 on 2020-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_auto_20201024_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_image',
            field=models.URLField(),
        ),
    ]
